### ISSUE TITLE
Model size confuse

### ISSUE THREAD

**Issue by zml24** [mit-han-lab/lite-transformer#12]
Hello, I read your paper and found that the smallest model size is 2.8M. However, I ran your config with the smallest embedding size (160) and found that the model size is about 5.2M. The embedding part model size is 8848 * 160 + 2 * 6632 * 160 = 3537920 ≈ 3.5M. So, how can I get the number 2.8M?

<img width="746" alt="image" src="https://user-images.githubusercontent.com/17996245/93549414-ce067c00-f99b-11ea-8f0e-f7513a26d9d1.png">

**Comment by Michaelvll** [comment]
Hi, thank you for asking! In the reported model size, we did not include the word embeddings. You can get the number by subtracting the number of parameters by the word embedding layer.

**Comment by Peter-1213** [comment]
I'm having the same question here. The parameters reported in the paper with this setting is 2.8M. However I can only get ~1.7M parameter size by calculating as below:
(ffn)160*160*2*12 + (attend2encoder)160*160*4*6 + (lsra)(80*80*4 + 80*80*2)*12 = ~1.69M. Which is consistent to the param size reported in this issue.
