### ISSUE TITLE
 Is there any guidance on preparing the cnndm dataset?

### ISSUE THREAD

**Issue by macn3388** [mit-han-lab/lite-transformer#14]
Is there any guidance on preparing the cnndm dataset?
I can not find any clue about how to download & prepare cnndm dataset. Any guidance would be thankful.

**Comment by Michaelvll** [comment]
Hi,
Thank you for asking! For downloading CNN / DM dataset, you can refer to the URL in the table at the bottom of the README: https://github.com/abisee/cnn-dailymail. : )
