### ISSUE TITLE
Is there any link for downloading iwslt14.de-en pretrained model?

### ISSUE THREAD

**Issue by macn3388** [mit-han-lab/lite-transformer#15]
It seems iwslt14.de-en pretrained mode was missed. 
Is the pre-training model of this dataset opened? If so, how can I get it?

**Comment by Michaelvll** [comment]
Hi, we did not have the pretrained model for iwslt14.de-en in this repo as the training time for that dataset is acceptable with 1 GPU. You could possibly try our training configuration and train the model by yourself. ; )
