### ISSUE TITLE
Could you please point out the core code, as there are too many fairseq code. Thank you!

### ISSUE THREAD

**Issue by guotong1988** [mit-han-lab/lite-transformer#19]
I am new to lite-transformer. 
@Michaelvll Thank you!
@chenw23 Thank you!

**Comment by guotong1988** [comment]
I guess 
https://github.com/mit-han-lab/lite-transformer/tree/master/fairseq/modules/lightconv_layer
https://github.com/mit-han-lab/lite-transformer/blob/master/fairseq/models/transformer_multibranch_v2.py

**Comment by Michaelvll** [comment]
Thank you for asking! The main logic of our design is placed in the [transformer_multibranch_v2.py](https://github.com/mit-han-lab/lite-transformer/blob/master/fairseq/models/transformer_multibranch_v2.py), and [multibranch.py](https://github.com/mit-han-lab/lite-transformer/blob/master/fairseq/modules/multibranch.py).
