### ISSUE TITLE
training config for wikitext103

### ISSUE THREAD

**Issue by pichuang1984** [mit-han-lab/lite-transformer#2]
Thanks so much for open-source your code!

Will it be possible to provide training/config for wikitext-103 dataset?

Thanks

**Comment by Michaelvll** [comment]
Thank you for asking! We just added the codes and configs in the new branch [language-model](https://github.com/mit-han-lab/lite-transformer/tree/language-model) with the pre-trained checkpoints.

**Comment by pichuang1984** [comment]
Thanks for providing the codes and configs. However it seems that the architecture transformer_lm_multibranch_v2_wiki103_small is not available in transformer_multibranch_v2.py?

**Comment by Michaelvll** [comment]
Hi, the model is in the file `lite-transformer/fairseq/models/transformer_lm_multibranch_v2.py` in the `language-model` branch.

**Comment by pichuang1984** [comment]
Thanks, you are right, I was still looking at transformer_multibranch_v2.py
