### ISSUE TITLE
Why do you recode the cpp code and cu code? What function is necessary?

### ISSUE THREAD

**Issue by guotong1988** [mit-han-lab/lite-transformer#20]
https://github.com/mit-han-lab/lite-transformer/tree/master/fairseq/modules/lightconv_layer

I am new to lite-transformer. Thank you!
@Michaelvll @chenw23

**Comment by Michaelvll** [comment]
Thank you for asking! The code is adapted from the [pytorch/fairseq](https://github.com/pytorch/fairseq). The lightconv and dynamicconv are proposed by Felix Wu et al. in "Pay Less Attention with Lightweight and Dynamic Convolutions". The cpp and cu codes are for better data layout when doing the computation for the proposed module. You could find how to install the codes at [installation section](https://github.com/mit-han-lab/lite-transformer#installation), and the explanation of the code at the [original codebase](https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper#memory-efficient-cuda-kernels). You could use the module without installing the cpp and cu codes (referring to the code in [lightweight_convolution.py](https://github.com/mit-han-lab/lite-transformer/blob/master/fairseq/modules/lightweight_convolution.py) and [dynamic_convolution.py](https://github.com/mit-han-lab/lite-transformer/blob/master/fairseq/modules/dynamic_convolution.py)), though you may not be able to load the pretrained models in the README.
