### ISSUE TITLE
What functions are achieved in the cu code?  The cu code is too hard for me to understand. Thank you.

### ISSUE THREAD

**Issue by guotong1988** [mit-han-lab/lite-transformer#21]
I am new to lite-transformer.

https://github.com/mit-han-lab/lite-transformer/blob/master/fairseq/modules/lightconv_layer/lightconv_cuda_kernel.cu

@Michaelvll @chenw23 Thank you very much.

**Comment by Michaelvll** [comment]
Please refer to the #20 . :)
