### ISSUE TITLE
Please share your quantization, quantization+pruning checkpoints

### ISSUE THREAD

**Issue by kishorepv** [mit-han-lab/lite-transformer#26]
Hi,

Can you please share the trained checkpoints for the quantized and quantized+pruned models (shown in this plot - https://github.com/mit-han-lab/lite-transformer#further-compress-transformer-by-182x)?

I am interested in testing it for the translation and the summarization tasks. I would appreciate it if you can share those checkpoints.

Thank you

**Comment by kishorepv** [comment]
@Michaelvll

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. Unfortunately, this repository is no longer actively maintained, so we will be closing this issue. If you have any further questions, please feel free to email us. Thank you again!
