### ISSUE TITLE
How to measure the FLOPs/MACs?

### ISSUE THREAD

**Issue by ranery** [mit-han-lab/lite-transformer#31]
Hi, thanks for your great work!

I am curious how you measure the flops/macs in your reported numbers, will the `torchprofile` package handle the measurement of the customized Cuda code?

Best,
Haoran

**Comment by Michaelvll** [comment]
Thank you for asking! We use the standard PyTorch code to measure the MACs, instead of the customized cuda code, so all of the computation of the ffn and attention/conv module is included in the reported number.

**Comment by sanwei111** [comment]
> Thank you for asking! We use the standard PyTorch code to measure the MACs, instead of the customized cuda code, so all of the computation of the ffn and attention/conv module is included in the reported number.

can you share the coder which calculate the (Mult-Adds and flop？
