### ISSUE TITLE
about the global and local features in fig 3

### ISSUE THREAD

**Issue by sanwei111** [mit-han-lab/lite-transformer#35]
as we know，the conventional attention module can capture features like fig 3.b（including diagonal and other positions）.   THIS ability is its nature，BUT i JUST wonder that when we add a branch that can capture  local features，the attention module can not capture feature like before，i.g，（including diagonal and other positions），while it just capture global feature！！！

**Comment by wwwadx** [comment]
Same question, how the model make sure that the attention layers capture the global information and the CNN layers capture local information with only one NLL loss? Have you figure it out?

> as we know，the conventional attention module can capture features like fig 3.b（including diagonal and other positions）. THIS ability is its nature，BUT i JUST wonder that when we add a branch that can capture local features，the attention module can not capture feature like before，i.g，（including diagonal and other positions），while it just capture global feature！！！

**Comment by sanwei111** [comment]
of course



---Original---
From: ***@***.***&gt;
Date: Tue, May 24, 2022 09:54 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mit-han-lab/lite-transformer] about the global and localfeatures in fig 3 (#35)




 
Same question, how the model make sure that the attention layers capture the global information and the CNN layers capture local information with only one NLL loss? Have you figure it out?
  
as we know，the conventional attention module can capture features like fig 3.b（including diagonal and other positions）. THIS ability is its nature，BUT i JUST wonder that when we add a branch that can capture local features，the attention module can not capture feature like before，i.g，（including diagonal and other positions），while it just capture global feature！！！

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. Unfortunately, this repository is no longer actively maintained, so we will be closing this issue. If you have any further questions, please feel free to email us. Thank you again!
