### ISSUE TITLE
about kernel size

### ISSUE THREAD

**Issue by sanwei111** [mit-han-lab/lite-transformer#37]
parser.add_argument('--decoder-kernel-size-list', nargs='*', default=[3, 7, 15, 31, 31, 31, 31], type=int)
 parser.add_argument('--encoder-kernel-size-list', nargs='*', default=[3, 7, 15, 31, 31, 31, 31], type=int)

as you c，above code is about the param of kernel size around the 6 encoder or decoder layer，i just wonder that why they don‘t keep same for 6 layers？？？

**Comment by Michaelvll** [comment]
Thank you for asking! We follow the setup from the [Pay Less Attention with Lightweight and Dynamic Convolutions](https://arxiv.org/abs/1901.10430).
