### ISSUE TITLE
wmt16_en_de dataset link

### ISSUE THREAD

**Issue by topbookcc** [mit-han-lab/lite-transformer#41]
hi, the download link of  the preprocessed wmt16_en_de data is invalid.
Can you provide the new link?
Thank you very much.

**Comment by realzza** [comment]
This dataset resouces [here](https://wit3.fbk.eu/2016-01) may be helpful.

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. Unfortunately, this repository is no longer actively maintained, so we will be closing this issue. If you have any further questions, please feel free to email us. Thank you again!
