### ISSUE TITLE
register_task of abstractive summarization

### ISSUE THREAD

**Issue by zhangyongwei756** [mit-han-lab/lite-transformer#8]
Could you share the code of the register_task of abstractive summarization? The effect of mine is not good, I don't know what the problem is.

**Comment by Michaelvll** [comment]
Thank you for asking! The configs for the abstractive summarization task is located in [configs/cnndm/attention/multibranch_v2/embed496.yml](configs/cnndm/attention/multibranch_v2/embed496.yml). You may have a try on that if you would like. We use [configs/cnndm/test.sh](configs/cnndm/test.sh) to evaluate the performance.
